<?php
	requireComponent('Bloglounge.Data.Caches');
	requireComponent('Bloglounge.Data.Tags');	
	requireComponent('Bloglounge.Data.FeedItems');	
	requireComponent('Bloglounge.Data.SkinSettings');
	requireComponent('Bloglounge.Model.Skin');
	requireComponent('Bloglounge.Model.SkinElements');
	requireComponent('Bloglounge.Model.Users');
	requireComponent('Bloglounge.Model.Boom');
?>